config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root "foods#index"
    get '/users/sign_out', to: 'users/sessions#destroy'
  end

  resources :foods, only: %i[index create new destroy]
  resources :recipes do
    resources :recipe_foods, only: %i[create new destroy]
  end
  resources :public_recipes, only: %i[index]
  resources :shopping_list, only: %i[index]

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, foreign_key: 'recipe_id', class_name: 'RecipeFood', dependent: :delete_all

  validates :name, presence: true
  validates :preparation_time, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :cooking_time, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :description, presence: true, length: { maximum: 250 }

  def total_food_items
    recipe_foods.length
  end

  def total_price
    price = 0
    recipe_foods.each do |r|
      price += r.quantity * r.food.price
    end
    price
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.includes(:recipe_foods, recipe_foods: [:food]).find(params[:id])
    @current_user = current_user
  end

  def create
    recipe = current_user.recipes.new(recipe_params)
    if recipe.save
      redirect_to recipes_path
      flash[:success] = 'Recipe was created!'
    else
      redirect_to new_recipe_path
      flash[:error] = 'ERROR! Recipe was not created.'
    end
  end

  def destroy
    Recipe.find(params[:id]).delete
    redirect_to recipes_path
  end

  def update
    recipe = Recipe.find(params[:id])
    recipe.toggle(:public)
    recipe.save
    redirect_to recipe_path(recipe)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/views/recipes/_food_table.html.erb
<tr class="row px-3 mx-0">
  <td class="col-5"><%= recipe_food.name %></td>
  <td class="col-2"><%= recipe_food.quantity_measure %></td>
  <td class="col-2"><%= recipe_food.value %></td>
  <td class="col-3 d-flex justify-content-around">
    <% if recipe_food.recipe.user == current_user%>
    <button class="btn btn-warning ">Modify</button>
    <%= button_to 'Delete', recipe_recipe_food_path(id: recipe_food.id, recipe_id: recipe_food.recipe_id), method: :delete, class: 'btn btn-danger btn-sm mb-2' %>
    <% end %>
  </td>
</tr>

app/views/recipes/_recipe.html.erb
<div class="recipe p-3 border container my-1">
  <div class="row">
    <div class="col-4">
      <%= link_to recipe.name, recipe_path(recipe), method: :get, class: "link-secondary" %>
      <%= button_to 'Delete', recipe_path(recipe), method: :delete, class: 'btn text-white btn-danger mt-3' %>
    </div>
    <div class="col-8">
      <p class="m-0"><%= recipe.description %></p>
    </div>
  </div>
</div>

app/views/recipes/_recipe_food_table.html.erb
<% if recipe_foods.length != 0 %>
<table class="recipe-foods-table container border border-dark border-2">
  <tr class="row px-3 label-row mx-0">
    <th class="col-5">Food</th>
    <th class="col-2">Quantity</th>
    <th class="col-2">Value</th>
    <th class="col-3">Actions</th>
  </tr>
  <% recipe_foods.each do |recipe_food| %>
    <%= render 'food_table', recipe_food: recipe_food, current_user: current_user %>
  <% end %>
</table>
<% else %>
<span>No Ingredients added!</span>
<% end %>

app/views/recipes/index.html.erb
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: "#{name}" %>
<% end -%>

<div class="recipe-container my-3 p-3 border border-dark rounded border-2">
  <div class="d-flex justify-content-between mb-3">
    <h2 class="mb-3">My Recipes</h2>
    <%= link_to 'Create Recipe', new_recipe_path, class: 'btn text-white  d-flex align-items-center btn-success' %>
  </div>
  <% if @recipes.length != 0%>
    <% @recipes.each do |recipe| %>
      <%= render 'recipe', recipe: recipe %>
    <% end %>
  <% else %>
    <span>No recipes added!</span>
  <% end %>
</div>

app/views/recipes/new.html.erb
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: "#{name}" %>
<% end -%>

<div>
  <h2>Create a Recipe!</h2>

  <%= form_with model: @recipe, class: 'd-flex flex-column border border-2 border-dark p-3' do |f| %>
    <div class="my-2">
      <%= f.label :name, "Name:" %>
      <%= f.text_field :name, placeholder: 'Name' %>
    </div>

    <div class="my-2">
      <%= f.label :preparation_time, "Preparation time:" %>
      <%= f.number_field :preparation_time, in: 0..300 ,placeholder: 'Minutes' %>
    </div>

    <div class="my-2">
      <%= f.label :cooking_time, "Cooking time:" %>
      <%= f.number_field :cooking_time, in: 0..300 ,placeholder: 'Minutes' %>
    </div>
    <%= f.label :description, "Description:" %>
    <%= f.text_area :description, placeholder: 'Write what this recipe is about!' %>
    <div class="my-2">
      <%= f.check_box :public %>
      <%= f.label :public, "Public Recipe!" %>
    </div>
    <%= f.submit "Submit", disable_with: 'Submiting...', class:'btn btn-success text-dark' %>
  <% end %>

  <div class="d-flex justify-content-star my-3">
    <%= link_to 'Go back', recipes_path, class: 'link-secondary text-decoration-none' %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="d-flex flex-column align-content-center my-3 p-3 border border-dark rounded border-2">
  <h2 class="align-self-center"><%= @recipe.name %></h2>
  <div class="">
    <div class="d-flex justify-content-between">
      <div class="my-2">
        <strong>Preparation time: </strong>
        <%= @recipe.preparation_time%>
      </div>
      <% if @recipe.user == @current_user%>
        <%= form_for @recipe, :method => :PUT do |f| %>
          <%= f.submit "public", class: 'btn btn-success text-white' if @recipe.public %>
          <%= f.submit "private" , class: 'btn btn-danger text-white' unless @recipe.public %>
        <% end %>
      <% end %>
    </div>
    <div class="my-2">
      <strong>Cooking time: </strong>
      <%= @recipe.cooking_time%>
    </div>
    <div class="my-2">
      <%= @recipe.description%>
    </div>
    <div class="d-flex justify-content-between">
      <%= link_to 'Generate shopping list', shopping_list_index_path , class: 'btn btn-success text-white'%>
      <% if @recipe.user == @current_user%>
        <%= link_to 'Add Ingredient!', new_recipe_recipe_food_path(@recipe), class: 'btn btn-success text-white' %>
      <% end %>
    </div>
  </div>
  <hr>
  <div class="">
    <%= render 'recipe_food_table', recipe_foods: @recipe.recipe_foods, current_user: @current_user %>
  </div>
</div>