config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root "foods#index"
    get '/users/sign_out', to: 'users/sessions#destroy'
  end

  resources :foods, only: %i[index create new destroy]
  resources :recipes do
    resources :recipe_foods, only: %i[create new destroy]
  end
  resources :public_recipes, only: %i[index]
  resources :shopping_list, only: %i[index]

end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, foreign_key: 'food_id', class_name: 'RecipeFood', dependent: :delete_all

  validates :name, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :measurement_unit, presence: true
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods
    @current_user = current_user
  end

  def new
    @food = Food.new
  end

  def create
    food = Food.new(food_params.merge(user_id: current_user.id))
    if food.valid?
      food.save
      flash[:notice] = 'Food added'
    else
      flash[:notice] = 'Could not add food'
    end
    redirect_to foods_path
  end

  def destroy
    Food.find(params[:id]).destroy
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/views/foods/index.html.erb
<div class="border border-2 border-dark rounded p-3 my-3">
  <div class="d-flex justify-content-between">
    <h2>Food list</h2>
    <% if signed_in?%>
      <%= button_to 'Add food', new_food_path, method: :get, class:"btn text-white btn-success"%>
    <%end%>
  </div>
  <table class="table border border-2 border-dark rounded p-3">
    <thead>
      <tr>
        <th class="col-3">Name</th>
        <th class="col-3">Measurement Unit</th>
        <th class="col-2">Price</th>
        <th class="col-4">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food|%>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.measurement_unit %></td>
          <td><%= food.price%></td>
          <td>
            <% if @current_user == food.user%>
            <%= button_to "Delete",food_path(food), method: :delete ,class:"btn text-white btn-danger btn-sm"%>
            <% end %>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<h1> Add Food!</h1>
<%= form_with model: @food, url: foods_path do |f| %>
  <div class="form-group">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, class:"form-control" %>
  </div>

  <div>
    <%= f.label :measurement_unit, "Measurement Unit" %>
    <%= f.text_field :measurement_unit, class: "form-control" %>
  </div>

  <div>
    <%= f.label :price, "Price" %>
    <%= f.number_field :price, class: "form-control" %>
  </div>

  <%= f.submit "Add" ,class:"btn btn-success text-white btn-md mt-3"%>
<% end %>