config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root "foods#index"
    get '/users/sign_out', to: 'users/sessions#destroy'
  end

  resources :foods, only: %i[index create new destroy]
  resources :recipes do
    resources :recipe_foods, only: %i[create new destroy]
  end
  resources :public_recipes, only: %i[index]
  resources :shopping_list, only: %i[index]

end

app/models/recipe_food.rb
class RecipeFood < ActiveRecord::Base
  belongs_to :food, class_name: 'Food'
  belongs_to :recipe, class_name: 'Recipe'
  validates :food_id, uniqueness: { scope: :recipe_id }
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def value
    "$#{quantity * food.price}"
  end

  def name
    food.name
  end

  def quantity_measure
    "#{quantity} #{food.measurement_unit}"
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def destroy
    RecipeFood.find(params[:id]).destroy
    redirect_to recipe_path(Recipe.find(params[:recipe_id]))
  end

  def new
    @recipe_food = RecipeFood.new
    @foods = Food.where(user_id: current_user)
    @recipe = Recipe.find(params[:recipe_id])

    redirect_to recipe_path(@recipe) unless @recipe.user == current_user
  end

  def create
    recipe_food = RecipeFood.new(recipe_food_params)
    recipe_food.food_id = params[:food_id]
    recipe_food.recipe_id = params[:recipe_id]

    if recipe_food.save
      redirect_to recipe_path(id: params[:recipe_id])
      flash[:success] = 'Ingredient was added!'
    else
      redirect_to new_recipe_recipe_food_path
      flash[:error] = 'ERROR! Ingredient already added.'
    end
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity)
  end
end

app/views/recipe_foods/_food_row.html.erb
<%= form_with model: @recipe_food, url: recipe_recipe_foods_path do |f| %>
  <tr class="row px-3 mx-0">
    <%= hidden_field_tag 'food_id', food.id %>
    <td class="col-4"><%= food.name %></td>
    <td class="col-2"><%= food.measurement_unit %></td>
    <td class="col-2 me-3"><%= f.number_field :quantity, class: 'w-100' %></td>
    <td class="col-3 p-0"><%= f.submit 'Add ingredient', class: 'p-1 btn btn-success text-white' %></td>
  </tr>
<% end %>

app/views/recipe_foods/_form_food_table.html.erb
<% if foods.length != 0 %>
<table class="foods-table container border border-dark border-2">
  <tr class="row px-3 label-row mx-0">
    <th class="col-4">Food</th>
    <th class="col-2">Measurement Unit</th>
    <th class="col-2">Quantity</th>
    <th class="col-4">Action</th>
  </tr>
  <% foods.each do |food| %>
    <%= render 'food_row', food: food, recipe_food: recipe_food %>
  <% end %>
</table>
<% else %>
<span>You have not added any food!</span>
<% end %>

app/views/recipe_foods/new.html.erb
<div>
  <h2>Add Ingredient!</h2>
  <div>
    <%= render 'form_food_table', recipe_food: @recipe_food,foods: @foods %>
  </div>

  <div class="d-flex my-3">
    <%= link_to 'Go back' , recipe_path(@recipe),
      class: "btn btn-secondary" %>
  </div>
</div>