config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root "foods#index"
    get '/users/sign_out', to: 'users/sessions#destroy'
  end

  resources :foods, only: %i[index create new destroy]
  resources :recipes do
    resources :recipe_foods, only: %i[create new destroy]
  end
  resources :public_recipes, only: %i[index]
  resources :shopping_list, only: %i[index]

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if signed_in? %>
        <div class="d-flex">
          <li class="nav-item">
            <span class="nav-link text-success">Welcome! <%= current_user.name%></span>
          </li>

          <li class="nav-item">
            <%= link_to "My Foods" , foods_path, method: :get, class:"nav-link link-secondary" %>
          </li>

          <li class="nav-item">
            <%= link_to "My Recipes" , recipes_path, method: :get, class: "nav-link link-secondary" %>
          </li>

          <li class="nav-item">
            <%= link_to "Public Recipes" , public_recipes_path, method: :get, class:"nav-link link-secondary" %>
          </li>
        </div>

        <li class="nav-item">
          <%= link_to "Sign Out" , destroy_user_session_path, method: :delete, class:"nav-link link-secondary" %>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up" , new_user_registration_path, class:"nav-link link-secondary" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign In" , new_user_session_path, class:"nav-link link-secondary" %>
          </li>
          <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeAppCapstone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/navbar" %>
      <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>